name: ✨ Feature request
description: Suggest an idea for this project
title: 'Feature request'
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem 📝
      description: A clear and concise description of what the problem is.
      placeholder: It's difficult when '...' happens because '...'.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution 💡
      description: A clear and concise description of what you want to happen.
      placeholder: It would be useful if '...' was possible.
  - type: textarea
    id: upstream
    attributes:
      label: Upstream effects 🚿
      description: Describe any anticipated upstream effects of this feature.
  - type: textarea
    id: downstream
    attributes:
      label: Downstream effects 🚿
      description: Describe any anticipated downstream effects of this feature.
